### PR TITLE
CORS enabled in main

### PR DESCRIPTION
**Pull request by Rahuljagwani**
Actually previous merge was in dev branch. As dev branch was not merged in main branch, therefor I created this PR.

### CODE REVIEW

**Comment by Rahuljagwani** [comment]
@pradeeban issue https://github.com/ControlCore-Project/concore/issues/38 can be closed after merging it.

**Comment by pradeeban** [comment]
Don't worry about the dev branch at this point. Ideally we would want to merge the pull request to the dev branch first, and then merge to main from dev time to time. But as of now, the dev branch is more used as the "experimental branch" with commits merged to main branch directly (contradicting the best practices, I am aware.)

As long as you submit your PR to one of the 2 branches (at this point, main), I will merge back to the other branch too (i.e., dev branch in this case). No need to create two separate pull requests. Just make sure to create pull requests to main from main and dev from dev. (So no bulky PRs with merge conflicts are included.)

**Comment by pradeeban** [comment]
I see your previous commit on this was to the dev branch. I will merge it to the main branch.

**Comment by pradeeban** [comment]
I have synced the main and dev branches. So closing this.

**Pull request closed without merging**
