### PR TITLE
Created Dockerfile.java.

### PR DESCRIPTION
**Pull request by Harshal-Rembhotkar**
Created Dockerfile.java, this file is essential for containerizing Java applications using Docker. It allows to define the environment and dependencies required for your Java application to run consistently across different platforms and environments. Kindly have a look.

### CODE REVIEW

**Comment by Harshal-Rembhotkar** [comment]
Please tell me @pradeeban, for this pull request, should I provide a README.md or not?

**Comment by pradeeban** [comment]
> Please tell me @pradeeban, for this pull request, should I provide a README.md or not?

A README or documentation is always a welcome addition for such major contributions.

**Comment by Harshal-Rembhotkar** [comment]
Got it.

**Comment by Harshal-Rembhotkar** [comment]
Hey @pradeeban, please review this PR.

**Comment by pradeeban** [comment]
Merging since these are two new files that won't impact anything. But changed the branch to dev. Pls send the future pull requests to the dev branch. The main branch is largely frozen.

**Pull request merged**
