### PR TITLE
Update contribute.py

### PR DESCRIPTION
**Pull request by parteekcoder**
Hi @pradeeban ,

 I changed the encoging from `utf-8` to `ascii` , I think which solves the problems. Give it a  try when you are available

### CODE REVIEW

**Comment by pradeeban** [comment]
/Users/pradeeban/concore/demo/sampleFile.graphml d/Users/pradeeban/concore/demo/controller2.py d/Users/pradeeban/concore/demo/sample3.graphml d/Users/pradeeban/concore/demo/rahul.graphml d/Users/pradeeban/concore/demo/generalcontrol.graphml d/Users/pradeeban/concore/demo/sampleC.graphml d/Users/pradeeban/concore/demo/controller2knob.py d/Users/pradeeban/concore/demo/sampleplothg.graphml d/Users/pradeeban/concore/demo/sample2knobplot.graphml d/Users/pradeeban/concore/demo/sample2.graphml d/Users/pradeeban/concore/demo/.DS_Store 'ascii' codec can't decode byte 0xf0 in position 1133: ordinal not in range(128) Some error Occured.Please try again after some time.

**Comment by pradeeban** [comment]
Honestly, I do not think changing to ascii will fix this issue.

**Comment by parteekcoder** [comment]
> /Users/pradeeban/concore/demo/sampleFile.graphml d/Users/pradeeban/concore/demo/controller2.py d/Users/pradeeban/concore/demo/sample3.graphml d/Users/pradeeban/concore/demo/rahul.graphml d/Users/pradeeban/concore/demo/generalcontrol.graphml d/Users/pradeeban/concore/demo/sampleC.graphml d/Users/pradeeban/concore/demo/controller2knob.py d/Users/pradeeban/concore/demo/sampleplothg.graphml d/Users/pradeeban/concore/demo/sample2knobplot.graphml d/Users/pradeeban/concore/demo/sample2.graphml d/Users/pradeeban/concore/demo/.DS_Store 'ascii' codec can't decode byte 0xf0 in position 1133: ordinal not in range(128) Some error Occured.Please try again after some time.

Yes @pradeeban you are right, but we found the issue .

if you check the last log
> Users/pradeeban/concore/demo/.DS_Store

This file is not present in the demo folder. I think this is the file that you system is making for its internal functionality. Can you please check if this file is visible to you

**Comment by parteekcoder** [comment]
So we can simply ignore hidden files as they always start with `.` .

What do you think about this

**Comment by pradeeban** [comment]
Oh, that is a weird folder automatically created by MacOS. So it was a MacOS-specific bug. No wonder you couldn't reproduce.

Anyway, great finding and fix.

**Pull request merged**
